[add] Added fireworks response
tsg-ut/slackbot pull request #326
Opened 2020-09-26 05:22 UTC by settyan117

「{リアクション名}花火」で花火を投下します(ex. 「koresuki花火」)。:reaction:花火でないのは、これだと花火の前が記号になってひでお花火が同時に起動してしまうため。

2020-09-26 06:57 UTC, hideo54 commented
「:reaction:花火」の方が絶対良くないですか? Slackのエディタの補完を使えないので不便だと思います。既存花火との干渉を避けたければ、そちらを変えればいい話。

2020-09-26 06:59 UTC, settyan117 commented
それはね、とてもわかるんですが、既存の花火も文化として残したくない？

2020-09-26 07:21 UTC, hakatashi commented
文化 is 何

2020-09-26 07:25 UTC, settyan117 commented
今までのログによって残されてる諸々的な（適当）

2020-09-26 07:26 UTC, settyan117 commented
まあそれにしてもこっちで「花火」に個別で反応すればええかとは思った

2020-09-27 08:22 UTC, hideo54 commented
既存を残したかったら、「花火」空打ちは hideo54 にする、とかでええと思うねんな (wcr は削除)

2020-09-27 11:04 UTC, hideo54 commented
テストが落ちている件、気になるようであれば、master を merge することで解決できます。もしまだ開発中であればぜひ。

2020-09-27 13:18 UTC, pizzacat83 commented
個人的にはなるべくcheckがall greenの状態でマージしてほしいので，↑を実行しておいてほしいです。

2020-09-27 13:30 UTC, pizzacat83 requested changes

2020-09-27 13:30 UTC, pizzacat83 commented on better-custom-response/custom-responses.ts
> +　　＿　　　　　　　＿`;
[SHOULD] `\n\` は不要で，バッククオートのなかで改行すればそのまま `\n` になります

2020-09-27 13:30 UTC, pizzacat83 commented on better-custom-response/custom-responses.ts
> +　　＿　　　　　　　＿`;
[MAY] バッククオート内のインデントは除去されないので，インデント0にして文字列を書いているのは正しいです。
ただ，周りとインデントがずれていてキモいと思うなら，その辺を直感的にやってくれるユーティリティが `common-tags` ライブラリにあります。
このリポジトリではよく `stripIndent` が使われていますが，変数展開が直感的に動く `source` の方が私はおすすめです。使い方は，リポジトリを `stripIndent` で検索して用例を探してください。 `source` の使い方も同じです。

2020-09-27 13:30 UTC, pizzacat83 commented on better-custom-response/custom-responses.ts
> +        outputFunction: input => [stripIndent`
[COMMENT] 意味論上は何も変わってないので問題はないんですが，配列終端のスペースがなくなっておらずかえってスタイルの統一性が損なわれています。もしスタイルを統一したいのであればESLintにやってもらうのがおすすめです。

2020-09-27 15:38 UTC, settyan117 commented on better-custom-response/custom-responses.ts
> +        outputFunction: input => [stripIndent`
（ちなみに、これらの更新はVSCodeのformat on saveを切り忘れててぐえっていました）

2021-01-20 13:23 UTC, hideo54 commented
これどうなってるんやろ @settyan117

2021-01-20 15:54 UTC, settyan117 commented
存在絵文字判定パートがめんどくてサボっています:pensive:

2021-01-20 16:37 UTC, settyan117 commented
:hoge:花火、:hoge: 花火、花火で発火します カスレポの花火は消す（花火以外は残す）

2021-01-20 18:58 UTC, hideo54 approved these changes
コロン入りを採ってくれてありがとう。
ぴざきゃさんが MAY としている通り、stripIndent することをおすすめしますが、その他は良いと思います (ちゃんと動いたっぽいし)

2021-01-21 12:58 UTC, settyan117 commented on better-custom-response/custom-responses.ts
> +　　＿　　　　　　　＿`;
stripIndentしました:ojigineko:

2021-01-21 13:07 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/113703)

2021-02-16 13:43 UTC, hideo54 commented
age

2021-02-18 04:16 UTC, merged