[add] Implemented 大麻雀
tsg-ut/slackbot pull request #337
Opened 2020-10-05 09:23 UTC by settyan117

[動画](https://www.youtube.com/watch?v=z8eKAUTZx80)を見かけて、面白そうだったので実装してみました。具体的なルールは以下の通りです。

- サンマ
- 役満縛り（役満以外で上がると錯和）
- 数え役満あり（48000点以上かどうかで判定）
- 開いているドラ表示牌にぶつかるまでは王牌も引ける（←これは理想で、カンがないので実装としては単純にツモ回数を20にしました。）
- 350000点スタート、600000点で勝利（配牌/サンマとは別得点）

2020-10-05 09:26 UTC, settyan117 commented
現行の立直は自動和了なので役満じゃない役で勝手に上がられるのは辛いかなとは思いましたが、ロンされると困る役満待ちは多分四暗刻シャンポン待ちか緑一色くらいなので、個人的には許容だと思います（対戦相手がこっちの手を読んでは来ないというハンデがあるし）

2020-10-05 09:37 UTC, settyan117 commented
ちなみに、四麻用実績の条件で大麻雀を排除しているのは、もし今後大麻雀が四麻に対応した場合に意図せず実績解除にならないためです（ツモ数多いから多少は解除しやすそうなので）

2020-10-13 22:50 UTC, hakatashi requested changes

2020-10-13 22:50 UTC, hakatashi commented on mahjong/index.js
> +			大麻雀Points: 350000,
[MUST] この実装だと既存のsavedStateを読み込んだときにプロパティがundefinedになってバグるのでObject.assignなどを使ってマージする実装にしてください

2020-10-13 22:50 UTC, hakatashi commented on mahjong/index.js
> +						state.大麻雀Points -= 1000;
[QUESTION] 役満聴牌せずに立直したばあい不聴立直にはならないっぽいけど、正しい?

2020-10-14 03:37 UTC, pizzacat83 commented on mahjong/index.js
> +			大麻雀Points: 350000,
まあマージを実装すると今後鯖に入れない人が機能追加しやすいというメリットがあります

2020-10-14 03:40 UTC, settyan117 commented on mahjong/index.js
> +						state.大麻雀Points -= 1000;
結論としては意図通りです
役満聴牌かの確認は多少実装が大変そうだったので、とりあえずは今の仕様のまま見送りました。はかたしはどっちの仕様の方がよさげに見えますか？
実装するならば、calculator.jsに全ての牌(or残ってる全ての牌←動画に合わせて空テンはノーテン扱いの場合)について上がり点を計算する関数を入れるとかかなぁ

2020-10-14 03:42 UTC, settyan117 commented on mahjong/index.js
> +			大麻雀Points: 350000,
なるのど〜
:riaru:

2020-10-17 04:21 UTC, hakatashi commented on mahjong/index.js
> +			大麻雀Points: 350000,
これにはすでに開発環境が整ってる人が新しいコードをpullしてきたときにエラーにならない意図もあります

2020-11-19 19:35 UTC, settyan117 commented
https://github.com/tsg-ut/slackbot/pull/337#discussion_r504297101
修正しました

2020-12-02 05:04 UTC, hakatashi approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/108563)

2021-02-21 14:13 UTC, merged