exercise実績の追加
tsg-ut/slackbot pull request #358
Opened 2020-11-11 10:25 UTC by domperor

exercise実績の追加です.
筋トレ，運動

2020-11-11 10:42 UTC, hakatashi requested changes
みました！

2020-11-11 10:42 UTC, hakatashi commented on sushi-bot/index.js
> +				.then(() => slack.reactions.add({name: 'sugoi', channel, timestamp}))
[MAY] 単にメインの実行をブロッキングしたくない (awaitしたくない) 意図なら

```suggestion
				slack.reactions.add({name: 'erai', channel, timestamp}))
				slack.reactions.add({name: 'sugoi', channel, timestamp}))
```
のほうがシンプルでわかりやすいと思います。

2020-11-11 10:42 UTC, hakatashi commented on sushi-bot/index.js
> +			exerciseCounter.add(user, score);
[SHOULD]

```suggestion
			exerciseCounter.add(user, 1);
```

が正しいと思います。

2020-11-11 10:42 UTC, hakatashi commented on achievements/achievements.ts
> +		condition: '180日運動する',
[SHOULD] 今の実装だと「180回運動したと発言する」になると思いますが、正しいですか？

2020-11-11 10:44 UTC, pizzacat83 commented on sushi-bot/index.js
> +				.then(() => slack.reactions.add({name: 'sugoi', channel, timestamp}))
unhandled promise rejection~~~

```suggestion
				Promise.all([
				  slack.reactions.add({name: 'erai', channel, timestamp}),
				  slack.reactions.add({name: 'sugoi', channel, timestamp}),
				])
```

2020-11-11 11:35 UTC, pizzacat83 commented on sushi-bot/index.js
> +				.then(() => slack.reactions.add({name: 'sugoi', channel, timestamp}))
あ、awaitしたくないのか (日本語が苦手)

2020-11-11 12:56 UTC, domperor commented on achievements/achievements.ts
> +		condition: '180日運動する',
ありがとうございます！其の通りですね，
直します……！

2020-11-11 13:06 UTC, domperor reviewed
よく見たらかっこの対応が:yokunasasou:です，直します〜〜

2020-11-11 13:12 UTC, domperor commented
直しました，お手隙の際にご確認くださると幸いですm(_ _

2020-11-11 14:54 UTC, hakatashi requested changes
テストが落ちているので確認してください。

2020-11-12 12:43 UTC, domperor commented
落ちているのはvoiperrobotなので大丈夫なはずです！

2020-11-12 18:29 UTC, hakatashi approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/106332)

2020-11-12 23:15 UTC, merged