sushi-bot: add riamu-counter/ranking
tsg-ut/slackbot pull request #393
Opened 2021-01-22 15:35 UTC by smallkirby

- sushi-botに「xxxりあむ」に対するリアクションとランキングを追加。
  - コードは他のランキングのほぼコピペ
  - Slack/複数人開発に疎いため不手際あれば教えてください:bow:

2021-01-22 15:56 UTC, pizzacat83 requested changes

2021-01-22 15:56 UTC, pizzacat83 commented on sushi-bot/index.test.js
> +		channel: slack.fakeChannel,
テストが落ちていて、原因は多分sandbox以外で反応しないようにしているのにテストでsandboxに送信していないからです。

2021-01-22 15:56 UTC, pizzacat83 commented on sushi-bot/index.test.js
> +		channel: slack.fakeChannel,
`process.env.CHANNEL_SANDBOX` を `slack.fakeChannel` にセットすることで、擬似的にメッセージがsandboxに送信された際の挙動のテストができます

2021-01-22 15:56 UTC, pizzacat83 commented on sushi-bot/index.test.js
> +		channel: slack.fakeChannel,
こうですかね (あんまりきれいじゃないのでまさかりください)

```js
describe('りあむ', () => {
	let stash = undefined;

	beforeAll(() => {
		const stash = process.env.CHANNEL_SANDBOX;
		process.env.CHANNEL_SANDBOX	= slack.fakeChannel;
	})

	it('react to もうむりあむ', ...);

	afterAll(() => {
		process.env.CHANNEL_SANDBOX = stash;
	});
});
```

2021-01-22 18:35 UTC, pizzacat83 commented
CIのエラーは多分 #394 で解決すると思います
#394 がmasterにマージされるのを待ってもいいですし、待たずに `riamu-counter` に `uninstall-word2vec` ブランチをマージして開発を続けても良いと思います

2021-01-23 03:44 UTC, smallkirby commented
ぐえ、色々とありがとうございます:bow: :bow: :bow:  
このブランチは練習用なのでこれ以上伸ばすつもりはないんですが、`uninstall-word2vec`ブランチをmergeしました(あってるんかなぁ、このやり方...)

2021-01-23 03:48 UTC, pizzacat83 commented
お、テスト通った :waiwai:

2021-01-23 03:50 UTC, pizzacat83 approved these changes

2021-01-23 03:51 UTC, pizzacat83 commented
![LGTM](https://image.lgtmoon.dev/113861)

2021-01-24 05:25 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/113890)

2021-01-24 05:28 UTC, cookie-s approved these changes
![](https://camo.githubusercontent.com/ad4cd84bfe1faac2c380579a84215fe3fa761c930320881f4098b62890c748f5/68747470733a2f2f696d6167652e6c67746d6f6f6e2e6465762f313133383631)

2021-01-24 10:13 UTC, smallkirby commented
以下の理由で閉じます:bow:
- よく考えたらランキングが既に多い(+ ランキングにするほどの意味のあるものではない)
- tsgbotに慣れる目的が主だったのでそんなにこの機能を積極的に入れたいわけではない。

2021-01-24 10:13 UTC, closed without merging