fix pocky: ポッキーゲーム中のノーマルポッキー投稿先
tsg-ut/slackbot pull request #395
Opened 2021-01-24 11:03 UTC by smallkirby

- ポッキーゲーム中のノーマルポッキーがポッキースレッドになることを修正ポッキー #359

2021-01-24 11:09 UTC, pizzacat83 requested changes

2021-01-24 11:09 UTC, pizzacat83 commented on pocky/index.js
> +	function postMessage(message, channel, broadcast = false, on_thread = false) {
これだと `broadcast` はデフォルト挙動に任せたいが `on_thread` は指定したい場合にぐえっとなります

JSだとこういう感じでやるといい感じになります

```js
	function postMessage(message, channel, options = {}) {
		const { broadcast, on_thread } = {
			broadcast: false,
			on_thread: false,
			...options,
		};
		// 以降 broadcast 変数と on_thread 変数をいい感じに使う
```

関数を呼び出す側はこう

```js
postMessage('hello', CHANNEL_SANDBOX, { on_thread: true })
```

2021-01-24 11:13 UTC, pizzacat83 commented on pocky/index.js
> +	function postMessage(message, channel, broadcast = false, on_thread = false) {
この `...` はPythonでいう `*hoge_list` とか `**hoge_dict` みたいな感じのものです

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2021-01-24 11:23 UTC, hakatashi requested changes
将来的に (今でもいい) thread内の発言にはthreadで返してあげたいので、postMessageに渡す引数はBooleanの `on_thread` じゃなく `threadId` みたいなのにしたほうがいい気がする

2021-01-24 11:23 UTC, hakatashi commented on pocky/index.js
> +    const {broadcast, on_thread} = {
[MUST] インデントおかしいにゃん

2021-01-24 11:23 UTC, hakatashi commented on pocky/index.js
> +      on_thread: false,
[SHOULD] ほかの部分だいたいcamelCaseなので (`thread_ts`とか Slack API の部分は除く) camelCaseのほうがよさそう

2021-01-24 11:23 UTC, hakatashi commented on pocky/index.js
> +        console.log(`thread: ${thread}`);
[MUST] デバッグ時のコードが残ってるにゃん

2021-01-24 11:23 UTC, hakatashi commented on pocky/index.js
> +	if (text === 'ポッキーゲーム') {
[MUST] インデントおかしいにゃん

2021-01-24 11:23 UTC, hakatashi commented on pocky/index.js
> +    const match = /([\s\S]+?)([？?]+)$/.exec(query);
[MUST] インデントおかしいにゃん

2021-01-24 11:25 UTC, pizzacat83 requested changes
ちなみに動作確認ってしましたか？ (これは追及ではなく質問です)

2021-01-24 11:25 UTC, pizzacat83 commented on pocky/index.js
> +    const match = /([\s\S]+?)([？?]+)$/.exec(query);
インデント直してください:pray:

2021-01-24 11:25 UTC, pizzacat83 commented on pocky/index.js
> +			postMessage(htmlEscape(result), channel, {broadcast: true, on_thread: false});
スレッドに投稿しないなら `broadcast: true` は意味を持たないと思います 🤔

2021-01-24 11:25 UTC, pizzacat83 commented on pocky/index.js
> +		`, process.env.CHANNEL_SANDBOX, {broadcast: false, on_thread: true});
このメッセージは `on_thread: false` だと思います (まあこのとき `thread` 変数が `null` になっているのでどう設定しても正しく動くんですが)

2021-01-24 11:54 UTC, smallkirby commented
動作確認はsandboxとDMの両方でしました > ぴざねこさん

2021-01-24 11:59 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/113897)

2021-01-24 12:11 UTC, pizzacat83 commented
ヨシ！ (画像略)

2021-01-24 12:11 UTC, pizzacat83 approved these changes

2021-01-26 02:29 UTC, kurgm approved these changes

2021-01-26 02:29 UTC, kurgm commented on pocky/index.js
> +		}
字数を減らしたければ：
```suggestion
		const {
			broadcast = false,
			threadPosted = null,
		} = postThreadOptions;
```

2021-01-26 03:52 UTC, hakatashi commented on pocky/index.js
> +		}
(もっと減らしたければ)

```suggestion
	function postMessage(message, channel, {broadcast = false, threadPosted = null} = {}) {
```

2021-01-26 08:50 UTC, merged