pwnyaa: pwnボットの追加
tsg-ut/slackbot pull request #397
Opened 2021-01-26 08:36 UTC by smallkirby

pwnの精進のお供としてpwnボットを追加したいです。
イメージとしては`sig-procon`で動いている競プロボットみたいな感じです。以下、簡単な概要です。

## 仕様
### 毎日やること
- TW/XYZの問題数をアップデート
- TWに登録してあるユーザのプロフィールを取ってきて、1日以内に解かれた問題があれば報告
- 実績解除がないか確認

### 毎週やること
- TWのユーザプロフィールを取ってきて週に解いた問題数でランキングを作りチャンネルで報告

### メンションでやること
- `list`: 登録してあるCTFの一覧表示
- `join`: CTFへの参加登録
- `check`: 登録してあるCTFのステータス/プロフィール確認

## Note
- 使用するチャンネルはsandboxにしたい
  - pwnチャンネルは人が少ないので...
  - dailyの報告は、誰も解いていなければ何も報告しない。よってそんなにチャンネルがうるさくなることもなさそう
- 一旦xyzは見た目だけ実装しているけど、登録はできないようになっている

2021-01-26 08:56 UTC, hakatashi commented
CIでESLintが正しく動いてないので `npm install @typescript-eslint/eslint-plugin@latest --save-dev` したほうがよさそう

2021-01-26 09:03 UTC, hakatashi commented
した

2021-01-26 14:34 UTC, hakatashi requested changes

2021-01-26 14:34 UTC, hakatashi commented on pwnyaa/index.ts
> +			channel: process.env.CHANNEL_SANDBOX,
[fyi] sandboxにpostすると流れちゃいそうなので#sig-ctfとかに流したい⋯⋯流したくない？

2021-01-26 14:34 UTC, hakatashi commented on pwnyaa/index.ts
> +			updateChallsTW();
[question] これ何

2021-01-26 14:34 UTC, hakatashi commented on pwnyaa/index.ts
> +						icon_emoji: ':pwn',
[MAY] バグってそう?

2021-01-26 14:34 UTC, hakatashi commented on pwnyaa/lib/TWManager.ts
> +import qs from 'qs';
[MUST] これ直してください (もしくはNode.js標準ライブラリの `querystring` を使う)

2021-01-26 14:38 UTC, JP3BGY commented on pwnyaa/index.ts
> +			channel: process.env.CHANNEL_SANDBOX,
#sig-pwn-tw とかにするべきでは

2021-01-27 12:57 UTC, smallkirby commented on pwnyaa/index.ts
> +			updateChallsTW();
この関数の意味ということなら、12時間毎に問題数をアップデートする関数です。

2021-01-27 14:36 UTC, smallkirby commented on pwnyaa/index.ts
> +						icon_emoji: ':pwn',
直しました

2021-01-27 14:41 UTC, smallkirby commented on pwnyaa/index.ts
> +			channel: process.env.CHANNEL_SANDBOX,
sandboxを使いたかったのはPRに書いた理由に加えて、新入生とかがぱっと見た時にjoinしてみようというノリになる0.000001%の可能性を考えたのと、毎週ランキングを発表するというランキング形式なのでsandboxと調和しそうという理由があります。
まあ、とりわけ強い希望があるわけでもないので一旦twチャンネルにしておきます。:bow: :bow: :bow:

2021-01-27 14:56 UTC, smallkirby commented
レビュー頂いたところを全て修正して、テストを書きました。

2021-01-27 14:56 UTC, smallkirby commented
[TODO] CHANNEL_TWを追加してもらう。

2021-01-27 16:37 UTC, hakatashi commented on pwnyaa/index.ts
> +			updateChallsTW();
ではなく、同じ関数を2回呼んでる点に対する疑問です (今見たら片方はXYZの間違いっぽい?)

2021-01-27 16:43 UTC, hakatashi requested changes

2021-01-27 16:43 UTC, hakatashi commented on pwnyaa/lib/TWManager.ts
> +				username: process.env.TWUSER,
[SHOULD] 前回のコメントで指摘し忘れてたんですが、環境変数はプロジェクト全体で共有されるものなので `TWUSER` はもう少しわかり易い名前がいいかな～と思います。`PWNABLE_TW_USERNAME` とか。`TWPW` も同様。

[nit] 新しい環境変数を追加した場合は `.env.example` に追加してもらえると助かります。

2021-01-28 01:48 UTC, smallkirby commented on pwnyaa/lib/TWManager.ts
> +				username: process.env.TWUSER,
環境変数の名前変更及び`.env.example`へ追加しました。

2021-01-28 01:49 UTC, smallkirby commented on pwnyaa/index.ts
> +			updateChallsTW();
あ、なるほど。`c8147aa`で修正してました :bow:

2021-01-28 05:24 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/114455)

2021-01-28 06:07 UTC, merged