bcr: 実績一覧単体で反応
tsg-ut/slackbot pull request #399
Opened 2021-01-28 04:02 UTC by smallkirby

「実績表示」単体で反応するようにしました。
- そのために`CustomResponse`インタフェースに`needUsername`を追加しました。

2021-02-16 15:18 UTC, settyan117 commented
masterをmergeしてもらえると、CIが新しい方になってえらいと思います（元ブランチもそのうちmergeします）

2021-02-16 17:22 UTC, hideo54 requested changes
僭越ながらレビューしました (見た目ばかり見ていて実装は全然見ていない :bow:)

2021-02-16 17:22 UTC, hideo54 commented on better-custom-response/custom-responses.ts
> +		achievements?: Achievement[],
[MUST] indent

2021-02-16 17:22 UTC, hideo54 commented on better-custom-response/custom-responses.ts
> +		needUsername?: true,
[MUST] indent

[MAY] こういう boolean だと `needsUsername` って命名にするのが一般的な気がするな〜〜〜と思いました

2021-02-16 17:22 UTC, hideo54 commented on better-custom-response/custom-responses.ts
> +				username: "実績一覧",
[MUST] indent

2021-02-16 17:22 UTC, hideo54 commented on better-custom-response/index.ts
> +							const responses = {}.hasOwnProperty.call(resp, 'outputArray') ? resp.outputArray :
[MUST] indent

2021-02-16 17:22 UTC, hideo54 commented on better-custom-response/custom-responses.ts
> +
[MUST] ここを空にしてしまうと挙動が変わってしまいます! 多分意図した変更ではないと思うんですが、commit 前に意図しない差分が入ってないか確認するようにしてください。

2021-02-17 10:29 UTC, smallkirby commented
インデント直して、bool変数名変えて、masterをmergeしました。:bow: あとお風呂にも入りました。:bow:

2021-02-21 15:49 UTC, hakatashi commented
これ review request されてるけどどういうプルリクやろ (マージ先がmasterでないのは何故)

2021-02-21 15:51 UTC, settyan117 commented
#341 に対する改善プルリクですね

2021-02-21 15:53 UTC, hakatashi commented
masterがマージされているからdiffがやばいことになってるのか (さすがにしないほうがよさそう)

2021-02-21 15:54 UTC, settyan117 commented
ずび…（CIが古くて落ちる状態だったのでマージしようぜ！ｗを軽率にしました）

2021-03-30 07:10 UTC, hideo54 commented
これヤバすぎて時が止まってるの草
幸い master を取り込んだとされているのは最新 1 commit のみっぽいので、雑にそれを revert したら直る気がするわね 知らんけど

2021-03-30 07:16 UTC, settyan117 commented
アッ、単にぼくがレビューできてないだけです…（ごめん…

2021-03-30 07:51 UTC, smallkirby commented
これ、自分で練習に作った記憶があるので閉じてもいいと思います。

2021-04-03 00:25 UTC, cookie-s commented
force-push ~~~ wwww
ｽﾞｫｰﾙﾋｰがあるんですね

2021-04-03 00:26 UTC, cookie-s commented
新たなPRでcherry-pickとかして手直しして再度動くか検証したほうがいいんじゃないですかね

2021-04-03 02:00 UTC, closed without merging