Scrapbox 改修
tsg-ut/slackbot pull request #410
Opened 2021-02-15 09:46 UTC by hideo54

暇だったので、行を指定して展開する機能を実装しました。Closes #197.

ついでに、rich text に対応しました。要は Scrapbox -> Slack の記法変換です。
まだ対応漏れがありそうな気もするけど、とりあえず思いついたケースには対応した。テストを見るとわかりやすいと思います。

2021-02-15 09:48 UTC, hideo54 commented
テストが意味わからん理由で落ちてんだけど

2021-02-15 10:07 UTC, hideo54 commented
しらんけど package lock 変えたせいかなあと思って revert したら test 直りました
テキトーなことしてすいません…
![IMG_1862](https://user-images.githubusercontent.com/4680738/107932480-f7661b00-6fc0-11eb-9a60-e7dbbb893ad5.jpg)

2021-02-15 10:19 UTC, hideo54 commented
`eslint --fix` で直せるやつだけ直しといたけど、他は何がしたいのかよくわからんので、これ導入したっぽい @hakatashi に任せる

2021-02-16 17:40 UTC, hideo54 commented
僕は犬に吠えられるの嫌なので、この Action を抜いてもらうか、ちゃんととことん対応するかどちらかにしたいんですが、@hakatashi 先生的にはどっちがいいと思いますか。
僕は前者派なんですが、後者ならちゃんとやります (そうするなら `eslint-plugin-jest` を入れる必要があり、hakatashi が入れた lint config をいじる必要があるので、どちらにしろ聞いておきたい)

2021-02-21 15:37 UTC, hakatashi requested changes
reviewdogの指摘が気になる場合は行単位か.eslintでignoreしてあげてください (個人的にはprefer-named-capture-groupとid-denylistはシュッと対応してほしい気がするが)。

あと `eslint-plugin-jest` は必要なくてeslintのenvにjestを指定すればjestのエラーは消えます

2021-02-21 15:37 UTC, hakatashi commented on scrapbox/index.ts
> +			let [, pageName,, lineId] = url.match(/^https?:\/\/scrapbox.io\/tsg\/([^#]+)(#([\da-f]+))?$/);
[SHOULD] `https://scrapbox.io/tsg/#zzz` とかが与えられたときにバグりそう。上のif文と正規表現を一致させたほうがいいと思います

2021-02-21 15:37 UTC, hakatashi commented on scrapbox/index.ts
> +	url: string;
[SHOULD] 博多市の書くBOTではセミコロンじゃなくカンマで統一されているのでカンマでお願いします

2021-02-21 15:37 UTC, hakatashi commented on scrapbox/index.ts
> +	s.replace(/\[(https?:\/\/.+)\]/g, '$1') // 外部リンク
[SHOULD] `[https://hoge.com] hoge [hoge]` とかが来たときにおかしくなる気がする

```suggestion
	s.replace(/\[(https?:\/\/.+?)\]/g, '$1') // 外部リンク
```

2021-02-21 15:37 UTC, hakatashi commented on scrapbox/index.ts
> +		.replace(/#([^\s]*)/g, '<https://scrapbox.io/tsg/$1|#$1>') // hashtag (TSG独自記法)
[nit] hashtagはTSG独自記法ではない

2021-02-26 11:29 UTC, hideo54 commented
@hakatashi
上の review で指摘された正規表現部分はまだ修正していないんですが、その前に質問です: TS の module の import 部分で、`.ts` を省略した import だと lint error が出ます。`.ts` をつけると lint error は消えますが、TS 的には error になると思います。これはどういう方向で解決するのが望ましいですか?

2021-02-26 12:54 UTC, hakatashi commented
放置していいけど `import/extensions` あたりをeslintrcでまるっとignoreしてもらえるとよいです

2021-02-26 14:23 UTC, hideo54 commented on scrapbox/index.ts
> +			let [, pageName,, lineId] = url.match(/^https?:\/\/scrapbox.io\/tsg\/([^#]+)(#([\da-f]+))?$/);
これ全く発想になかったから助かりました。

2021-02-26 14:23 UTC, hideo54 commented on scrapbox/index.ts
> +	s.replace(/\[(https?:\/\/.+)\]/g, '$1') // 外部リンク
ありがとうございます! 他にも最短一致で書くべきところがあったのでまとめて改良しました。

2021-02-26 14:24 UTC, hideo54 commented
ご指摘をまるっと解決したつもりになったので、再度 review 願いたいです。

2021-02-27 08:11 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/113889)

2021-02-27 08:13 UTC, hideo54 commented
やったー

2021-02-27 08:14 UTC, hideo54 commented on scrapbox/index.ts
>  					url: 'https://slack.com/api/chat.unfurl',
裏話: ここを Slack SDK に移したいなと思ったが、test をまるっと書き換える必要があり苦しかったので棚上げにした

2021-02-27 08:15 UTC, merged