[add] Implemented cfp tags
tsg-ut/slackbot pull request #414
Opened 2021-02-18 06:54 UTC by settyan117

context free postにおいて、完全にランダムな単語ではなく、cfp-tags.tsに記述された単語配列の中からランダムに埋め込む機能を実装しました。例えば、cfp-tags.tsでtags = {"nums": ["1", "20", "5000兆"]}としたときに、{<nums>}は["1", "20", "5000兆"]の中からランダムに選ばれた文字列に変換されます。
従来の{}に名前を付ける機能（{hoge}みたいな）は、タグ付きcfpでも、タグの後ろに名前をつけることで同じ効果が得られます（{<nums>num1}など）。この場合、同じタグかつ同じ名前（つまり括弧の中身が完全一致）のplaceholderに同じ単語が挿入されます。

2021-02-18 06:54 UTC, settyan117 commented
今の所単語を選ぶもとは配列だけですが、少しいじれば関数とかにも対応できそう？

2021-02-18 14:58 UTC, KPCCoiL requested changes
:furuikeya::yy::erai::genius:
書いたとことeslintで言われてるとこだけお願いします

2021-02-18 14:58 UTC, KPCCoiL commented on context-free/cfp-tags.ts
> +export const tags: {[key: string]: Array<string>} = {
[SHOULD] これでも動くんですけど、こういう連想配列的なことをするときは`Map`を使うのがお行儀がいいとされていた気がします

2021-02-18 14:58 UTC, KPCCoiL commented on context-free/index.ts
>        await sleepFor(5000);
[SHOULD] リクエストを飛ばさない場合に5秒待つのは無駄なので、いい感じにするとより良いと思います

2021-02-18 16:21 UTC, settyan117 commented on context-free/index.ts
>        await sleepFor(5000);
tagを参照している場合を排除して、先頭以外で5秒まつようにしました

2021-02-18 16:21 UTC, settyan117 commented on context-free/cfp-tags.ts
> +export const tags: {[key: string]: Array<string>} = {
:riaru: なおしました

2021-02-18 16:24 UTC, settyan117 commented
"Use plural nouns to name array variable"はおそらく変数matchについて言われてるやつだと思いますが、これをmatchesとするのは不自然だと思うので現状そのままにしています。
Array destructingは、phTagへの格納で判定が必要あることから結局うまくまとめられないと思っているので、これも現状そのままです。
コメントあればよろしくおねがいします

2021-02-19 02:20 UTC, KPCCoiL commented
正規表現のグループに名前をつけてねって言われてるの直せばインデックスアクセスしなくて良くなるし:dog:の文句全部消せる気もしています(ダメだったらすいません)
hidden conversationの中にあるとかで見落としちゃってませんか

2021-02-19 02:27 UTC, settyan117 commented
hidden conversationってなんですか？（無知）

2021-02-19 02:30 UTC, KPCCoiL commented
こういう(中略)みたいなやつです そもそもレビュー内容は"Files changed"からの方が見やすいかもですが
<img width="879" alt="image" src="https://user-images.githubusercontent.com/4506345/108448704-916de200-72a5-11eb-93cc-46b822d3e8fd.png">

2021-02-19 02:31 UTC, settyan117 commented
アッ（JSの構文とかの話かと思った） 確認します…

2021-02-20 03:03 UTC, KPCCoiL approved these changes
よさそう! :waiwai::pro:

2021-02-20 03:19 UTC, merged