actions: migrate to Node.js latest
tsg-ut/slackbot pull request #429
Opened 2021-03-03 13:34 UTC by ishitatsuyuki

2021-03-03 13:38 UTC, ishitatsuyuki commented
ついでにpackage-lock.jsonも最新のnpmのやつに変えてます

2021-03-03 13:41 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/114143)

2021-03-03 13:49 UTC, hakatashi requested changes
マージ前にテストは通してほしいですね～ (たぶん Unhandled Promise Rejection で落ちてるのでちゃんとbep-eng.dicをモックしてあげる必要がありそう)

2021-03-05 04:53 UTC, ishitatsuyuki commented
FUCKING FINALLY

2021-03-05 04:53 UTC, merged