AmongYou: AmongUsボットの追加
tsg-ut/slackbot pull request #437
Opened 2021-03-27 12:44 UTC by smallkirby

Amongusをやりたい人を募るAmongUsボットを追加したいです。概要は以下のとおりです。  

## UI
- Block Kitを利用しています。
- 参加希望条件についてはモーダルで表示させます。

## 使用チャンネル
- `#sig-among-us`
- `#sandbox`
  - 基本的にamongusチャンネルでの利用を想定していますが、sandboxでも利用できるようにしています。

## 用法
- Slashコマンド(`/amongyou start`)で応募を開始する。
![Screenshot from 2021-03-27 21-33-35](https://user-images.githubusercontent.com/47111091/112720840-236fa700-8f44-11eb-880a-ef9b69cb16f8.png)
- `JOIN!`を押すとモーダルが開き、**参加可能時刻** と **希望最低人数** を選択できる。
![Screenshot from 2021-03-27 21-37-25](https://user-images.githubusercontent.com/47111091/112720945-b4df1900-8f44-11eb-9424-a1d9cf1972a7.png)
- 現在の参加状況は一つのスレッドを編集していく形で更新する。(`stat`コマンド等は必要ない)
![Screenshot from 2021-03-27 21-39-49](https://user-images.githubusercontent.com/47111091/112721014-fb347800-8f44-11eb-8b57-28e8c1e25990.png)
- 参加可能時刻と希望人数から、開催可能な状態になったら通知を行う。
![Screenshot from 2021-03-27 21-40-31](https://user-images.githubusercontent.com/47111091/112721028-13a49280-8f45-11eb-8df4-f04f0cc4b7b6.png)
- なお、`参加取り消し`を押すと参加をキャンセルでき、現在の参加状況に反映される。

## TODO
- `.env`に`CHANNEL_AMONGUS`の反映
- スラッシュコマンドの登録(`/slash/amongyou`)

resolve #436

2021-03-27 14:40 UTC, hideo54 requested changes
実装はえ〜〜〜 お疲れさまです! すげ〜〜〜
あまり真面目に見ていない割に些細な指摘ばかりで恐縮なんですが、レビューいたしました。
あとは
* 全体的にインデントが統一されておらず、乱れている (なんで reviewdog 反応せえへんのやろ…)
* ぜひ CODEOWNER に名を連ねてくださいませ
あたりもよろしくお願いします。

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +const timeList = [
[MAY] 力技で草。まあいうて読みやすいしこれでも良いか。
一応貼っておくと
```
const timeList = lodash.range(0,24).map(n => {
  const h = n.toString().padStart(2, '0');
  return [ h + ':00', h + ':30' ];
}).flat();
```
みたいにも書けます。

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +	timeEnd: Date,
[MUST] インデントがおかしい。以下も同様 (以下略)。

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +	return `${jpDate.getUTCMonth() + 1}/${jpDate.getUTCDate()} ${(`00${String(jpDate.getUTCHours())}`).slice(-2)}:${(`00${String(jpDate.getUTCMinutes())}`).slice(-2)}`;
[SHOULD] 苦労の跡が見えるw dayjs とか moment とか使えばかなりすっきり書けます。この slackbot の dependency にあるのは moment だけど、もう非推奨なので、まあお好みで。
たとえば dayjs なら
`dayjs(date).format('MM/DD HH:mm')`
みたいに書けます。読みやすいね。ぜひこれ使ってくださいませ。(moment でも多分全く同じコード)
https://day.js.org/docs/en/display/format

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +			text: '*参加可能時刻* を *希望最低人数* 選んでね! :among_us_red:',
[MAY] 日本語おかしくない? しらんけど

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +		text += `<@${user.slackId}> `;
[COMMENT] .map 使えば綺麗にかけそう。template literal 内に
```
${amongableUsers.map(user => `<@${user.slackId}>`).join(' ')}
```
って書けるし。関数要らないまである。

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +	let text = `*AmongUsが開催できるよ〜〜* (${amongableUsers.length}) :among_us_report: :among_us_report:\n`;
[COMMENT] 言葉遣い的な指摘で恐縮なんですが `(3)` よりかは `(3人)` みたいに書いてあると嬉しいかなと思いました

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +				text: '既に募集は開始してるよ',
[COMMENT] 日本語おかしくない? というのと、語尾に句点か絵文字か「〜」が欲しいです (僕だけ? だったらごめん…)

2021-03-27 14:40 UTC, hideo54 commented on amongyou/index.ts
> +				text: '今は募集してないよ',
語尾(ry ごめん…

2021-03-28 06:44 UTC, hideo54 requested changes
ありがとうございます! 日本語完璧だと思います! お疲れさまです!
しかし、指摘を追加してしまいました。最初のレビューで見逃していてすいません…
あと、なぜか reviewdog 反応していませんが (なんで?) eslintrc を追加しているということは lint する気があるということだと思うので、fix して欲しいです。インデント関係を中心に 57 problems 出ています。(大体は `fix` で自動で解決されそう)

2021-03-28 06:44 UTC, hideo54 commented on amongyou/index.ts
> +const parseDate = (strDate: string) => {
[SHOULD] 多分 BlockKit から取った options を入力にしているので変な突かれ方はしないとは思うんですが、(moment を使うことにしたようなので moment の話をします) moment を使うとこの関数も1行で済みます。
```
> moment('12:34', 'HH:mm')
Moment<2021-03-28T12:34:00+09:00>
```
あと個人的には、過去の時間が入力された場合は翌日に設定されていると嬉しいです。これも moment だとすごく簡単に書けて、
```
const date = moment(strDate, 'HH:mm');
if (date < moment()) { // moment() は現時刻になります
  date.add(1, 'day');
}
return date
  .toDate(); // 最終的に標準 Date で管理したい場合
```
ってすれば良いです。こうすると「1:00」と入力してもちゃんと翌日1時になると思います。

ンマ〜〜これでも0:00に「22:00 - 1:00」とか入力してくる TSGer がいたりすると余裕でバグりそうわね〜〜
`after` みたいな optional argument を取っておいて、`setEndTime` 内で `parseDate()` を呼ぶときにはそれに start time を入れるようにして、この関数で
```
if (date < moment() || date < after) {
```
するのが順当かなあ…?

いっそプログラム全体の date 系を全部 moment object で管理するようにするのもアリだと思うけどまあどっちでも面倒さ大差ないかもしらんな。お任せします

最初のレビューの時見逃しててごめんなさい…

2021-03-28 08:35 UTC, smallkirby commented on amongyou/index.ts
> +const parseDate = (strDate: string) => {
めちゃくちゃ丁寧に有難うございます! :bow: 
- 時刻の選択リストを、現在時刻を起点として30分時刻で提示し、24時を回ると00:00から表示するようにしました。
```ts
const timeList = range(moment().hours(), moment().hours() + 24).map((n) => {
	const h = (n % 24).toString().padStart(2, '0');
	return [`${h}:00`, `${h}:30`];
}).flat();
```
- 過去の時刻が入力された場合には翌日の時刻として解釈するようにしました。但し、「17:13現在の今すぐ始められる」という場合のために「17:00」のような選択肢も提示する必要があるため、現在との時刻のdiffが30分以内の過去の時刻は当日の時刻として解釈するようにしました。
```ts
const parseDate = (strDate: string) => {
	const date = moment(strDate, 'HH:mm');
	if (moment().diff(date, 'minutes') >= 30) {
		date.add(1, 'day');
	}
	return date.toDate();
};
```
- 時刻のバリデーションは一応入れてあります。
```ts
			if (now.getTime() >= user.timeStart.getTime() && now.getTime() <= user.timeEnd.getTime()) {
```

2021-03-28 09:06 UTC, smallkirby commented
レビューいただいた点を直しました。:bow:
Lintに関しては、手元でやってもインデント関係のエラーが出なかったので、eslintrcをhakatashiのものからGoogleのものに変えてみましたが、治ってたりするのかな...。関係あるのかな...。

2021-03-28 09:49 UTC, hideo54 commented on amongyou/index.ts
> +const parseDate = (strDate: string) => {
オッいいですね〜〜 (validation, 見逃しててすいません…) すごく良いと思います!

2021-03-28 10:06 UTC, hideo54 approved these changes
よさそー! お疲れさまです! やったー! 嬉しい! わいわい!
(手元で動かしてみて無事動いているという前提でよさそうと言っているので、もしまだだったら、それだけよろしくお願いします :bow:)

2021-03-28 10:07 UTC, hideo54 commented
> Lintに関しては、手元でやってもインデント関係のエラーが出なかったので、eslintrcをhakatashiのものからGoogleのものに変えてみましたが、治ってたりするのかな...。関係あるのかな...。

なさそー。しらんけど。なんでやろなあ。
まあどんな rule でもいいんですが、インデントの fix だけはよろしくお願いします :bow:

2021-03-28 10:42 UTC, smallkirby commented
:heavy_check_mark: `.env`の変更
:heavy_check_mark: slashコマンドの追加
:question: え、まだインデント変なところあるのかな...。eslint君が動いてくれないぽよ。。。

2021-03-28 19:25 UTC, hideo54 commented
僕もなんで `npx eslint amongyou/index.ts` が動かないのか知らないんですが、`npx eslint amongyou/.eslintrc.json` だと動きますね

2021-03-29 00:55 UTC, smallkirby commented
それ、`index.ts`じゃなくて、`.eslintrc.json`の方をリントしていませんか...?

2021-03-29 00:59 UTC, smallkirby commented
あれ、もしかして今までのインデントとかって`.eslintrc.json`自体の話ししてましたか...?

2021-03-29 09:45 UTC, hideo54 commented
あ、なるほどなるほど、ほんまや、すいません…
怒られてるのは .eslintrc.json のみですね…
(てっきり index.ts もこれ怒られるだろと思うところあったけど試してみたらそんなことはなかった)
じゃあまあ大丈夫です 🆗  (.eslintrc.json の rules のところのインデントがおかしいところくらいは直した方がいいんじゃないかと思いましたが、まあ)

2021-03-29 10:11 UTC, smallkirby commented
直しました！ありがとうございます:bow:
マージしちゃいます。

2021-03-29 12:01 UTC, merged