Dev platypus/hangmanbot
tsg-ut/slackbot pull request #460
Opened 2021-04-17 08:11 UTC by platypus999

hangman
_ _ _ _ _ _ _

2021-04-17 11:00 UTC, hideo54 requested changes
天才開発カモノハシ :tada: 楽しいゲームをありがとう……
僭越ながらレビューしましたので、よろしくお願いします。
あと抵抗がなければぜひ CODEOWNERS にも名を連ねていただけると!

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +    var newOpenList = state.openList.slice();
[SHOULD] const にしましょう!

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +    var letterCount = 0;
[SHOULD] let にしましょう!

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +    for (const index in range(state.answer.length)) {
[MUST] range を使っているのを見るに配列の中身を取り出したいのでしょうが、それ (Python の for in) は for of です。今回は in でも本当にたまたま動きますが、直しましょう。
ちなみに、range を使わなくても
```
for (const [index, char] of state.answer.entries())
```
みたいに書けます。

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +    console.log(freqLeft + " " + freqRight);
[SHOULD] これは手元でのデバッグ用が残ってしまっている感じかな…? 消すか、もし本番でもデバッグ用にログを残したいなら、logger を使ってほしいです。以下同様。

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +    if (state.triesLeft == numberOfTries) {
[MUST] `===` 使いましょう! 以下同様。

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +    if (state.answer.match(/x|z|j|q/)) {
[COMMENT] 知っててやってるなら申し訳ないんですが、`/[xzjq]/` と書けます

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +                    case "easy": diffValue = 0; break;
[SHOULD] これわざわざ diffValue を用意する意味とは…? って思っちゃった。無駄に読みにくくなってしまっていそう。

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +const HangmanResponse = {
[SHOULD] これわざわざ用意する意味とは…? って思っちゃった。無駄に読みにくくなってしまっていそう。

2021-04-17 11:00 UTC, hideo54 commented on hangman/index.js
> +    return 'hangman';
[SHOULD] これ意味が伝わらないと思うので、適切なエラー処理になっていると嬉しいなあ

2021-04-17 11:03 UTC, hideo54 commented
これは単なるわがままなんですが、ゲームが始まると「答えてね〜」って言ってスレッドを開いてくれると、時間が1秒くらい節約されて嬉しいです (は?)

2021-04-17 11:06 UTC, platypus999 commented on hangman/index.js
> +const HangmanResponse = {
これ、C/C++のenumのノリで書いたコードなんですが、ただの整数にエンコーディングするのがJavascriptでは一般的なんでしょうか…？

2021-04-17 11:06 UTC, ishitatsuyuki commented on hangman/index.js
> +const HangmanResponse = {
JSの主流はstringですよ笑

2021-04-17 11:18 UTC, hideo54 commented on hangman/index.js
> +const HangmanResponse = {
エンコード方法がよっぽど自明でない限り、数字に割り当てると、コードを読む時のわかりやすさがかなり落ちてしまうので、`'success'` みたいに文字列に入れることが多いです。

2021-04-17 11:20 UTC, platypus999 commented on hangman/index.js
> +    return 'hangman';
これ、エラーだと思ってあまり書いてなかったんですが (なんなら運がとてつもなくいい人向けのイースターエッグとまで思っていた) やっぱりエラー処理したほうがよさそうですか？

2021-04-17 11:21 UTC, hideo54 commented on hangman/index.js
> +    return 'hangman';
草 あ〜〜じゃあこのままの方が面白い気がするな、これで行きましょうか (ありがとうございます)

2021-04-17 11:47 UTC, platypus999 commented on hangman/index.js
> +    for (const index in range(state.answer.length)) {
`entries()`を用いた書き方を手元で試してみたのですが、Stringにentriesはないよみたいなことを言われます…

2021-04-17 11:48 UTC, hideo54 commented on hangman/index.js
> +    for (const index in range(state.answer.length)) {
あ、ごめん、answers 配列だと思ってたわ… (目がついていない)

2021-04-17 11:49 UTC, hideo54 commented on hangman/index.js
> +    for (const index in range(state.answer.length)) {
しかも answer (singular) って書いてんじゃん… すいません、ちなみにの項は忘れてください…

2021-04-17 12:15 UTC, hakatashi requested changes

2021-04-17 12:15 UTC, hakatashi commented on hangman/index.js
> +                await setState({
[MAY] 今のコードだと race condition が発生するのでmutex.runExclusiveを使うとよりよくなります 面倒なら大丈夫です

2021-04-17 12:15 UTC, hakatashi commented on hangman/index.js
> +        return await postMessage(stripIndents`${header}
[SHOULD] 最初のバッククオートの後に改行入れないと stripIndents が効かないので、stripIndentsを消すか最初に改行を入れるかしてください。以下同様

2021-04-17 12:15 UTC, hakatashi commented on achievements/achievements.ts
> +		condition: 'HangmanでX, Z, J, Qのいずれかを含む単語でゲームクリアする',
[SHOULD] 説明文がおかしいです

2021-04-17 12:18 UTC, hakatashi commented on hangman/index.js
> +        return await postMessage(stripIndents`${header}
stripIndentsじゃなくてstripIndentの話をしていました⋯⋯ (泣)

2021-04-17 12:28 UTC, platypus999 commented on hangman/index.js
> +        await increment(state.user, 'hangman-letters', succeeded);
これ実はletterCountの間違いでした！(草 (草じゃあないんだよ))
直しました…

2021-04-17 12:37 UTC, platypus999 commented on hangman/index.js
> +const state = (() => {
ごめんなさい、将来余裕が出たときの課題とさせてください… :pray:

2021-04-17 18:01 UTC, hakatashi requested changes

2021-04-18 12:04 UTC, platypus999 commented
一旦これで merge したいと思います (test は、もっと jest の動作を理解してから書きたいと思います)

2021-04-18 12:09 UTC, hideo54 approved these changes
たぶん良い! おつかれ! 最高! ありがとう!
![](https://pbs.twimg.com/media/DSJCk8lU8AAh_78.jpg)

2021-04-18 13:20 UTC, hakatashi approved these changes
よさそう! お疲れさまでした!

![LGTM](https://image.lgtmoon.dev/124011)

2021-04-18 13:25 UTC, merged