Discord-TTS supports voicetext
tsg-ut/slackbot pull request #494
Opened 2021-05-28 14:40 UTC by Yosshi999

APIキーが一個増えてます

2021-05-28 18:04 UTC, hakatashi requested changes

2021-05-28 18:04 UTC, hakatashi commented on discord/speeches/voicetext.ts
> +			validateStatus: (status) => (status === 200),
[QUESTION] これがデフォルト値だと思っているんですが、必要ですか?

2021-05-28 18:04 UTC, hakatashi commented on discord/speeches/types.d.ts
> +	meta: {speed: number, emotion?: string, emolv?: number}
[MAY] string, number より Emotion, EmoLV のほうがいいかな～って思いますが、どうですか

2021-05-28 18:04 UTC, hakatashi commented on discord/tts.ts
> +			if (tokens[0]?.toUpperCase() === 'TTS-DEV') {
[MUST] もどす

2021-05-29 14:19 UTC, Yosshi999 commented on discord/speeches/voicetext.ts
> +			validateStatus: (status) => (status === 200),
https://github.com/axios/axios/blob/master/lib/defaults.js#L100-L102
その通りですね。削除します

2021-05-29 14:33 UTC, Yosshi999 commented on discord/speeches/types.d.ts
> +	meta: {speed: number, emotion?: string, emolv?: number}
なんかimportの依存関係がよく分からなくなってこうしてしまったんですが、やっぱり全体で統一したほうが良いですよね

2021-05-29 15:12 UTC, hakatashi approved these changes
LGTM

2021-05-29 15:12 UTC, Yosshi999 commented
手元でコンパイルエラーが起こってるのでテストが通っててもまだマージしないでください

2021-05-29 16:29 UTC, Yosshi999 commented
ok

2021-05-31 03:42 UTC, hakatashi approved these changes
コードは良さそう。いちおうデプロイ前にLintエラー直しておいてもらえると～

2021-05-31 14:33 UTC, merged