文豪クイズ・文豪当てクイズ
tsg-ut/slackbot pull request #545
Opened 2021-11-14 18:01 UTC by Yosshi999

2021-11-14 18:04 UTC, hakatashi requested changes

2021-11-14 18:04 UTC, hakatashi commented on bungo-quiz/index.ts
> +        const cards: string[] = JSON.parse(readFileSync(problemsPath).toString());
[MUST] Sync系メソッドは使用禁止です

2021-11-14 18:57 UTC, settyan117 commented on bungo-quiz/problems.json
> +]
これ、自動取得とかにはならない感じですか？（仕様がわかっていない）

2021-11-14 19:32 UTC, hideo54 requested changes
Thanks for making awesome quiz bot!

2021-11-14 19:32 UTC, hideo54 commented on bungo-quiz/index.ts
> +  const { data } = await axios.get<string>(
これ、普通に `axios.get<string>('https://...');` じゃダメだった感じですか? ぱっとみそれでいいように見える (違ったらすいません)

2021-11-14 19:32 UTC, hideo54 commented on bungo-quiz/index.ts
> +import cherrio from 'cheerio';
[MUST] typo してます! (以後同様)

2021-11-14 19:32 UTC, hideo54 commented on bungo-quiz/index.ts
> +import { readFileSync } from 'fs';
博多市の言う通りで、加えて言うと `from 'fs/promise'`  おすすめです

2021-11-14 19:32 UTC, hideo54 commented on bungo-quiz/index.ts
> +        const cards: string[] = JSON.parse(readFileSync(problemsPath).toString());
博多市の言う通りなんですが、加えていうと、`.toString()` しなくても `readFile(problemsPath, 'utf8')` 等すると文字列型扱いしてくれます

2021-11-15 12:54 UTC, Yosshi999 commented on bungo-quiz/index.ts
> +  const { data } = await axios.get<string>(
青空文庫の本文は恐らくすべてshift-jisでエンコードされており、一方axiosは暗黙的にutf-8にデコードしてしまうのでこのようにBufferを経由しています

2021-11-15 13:46 UTC, Yosshi999 commented on bungo-quiz/problems.json
> +]
最新を拾うことにしました

2021-11-15 13:50 UTC, Yosshi999 commented
仕様を少し変更しました

毎回ランキングページへ行き、最新版のアクセス数ベスト500を取得するようにしました

2021-11-15 14:28 UTC, Yosshi999 commented
完成しました

2021-11-15 18:10 UTC, settyan117 commented on achievements/achievements.ts
> +	},
デプロイされて異常者が生まれだして、あとで「ヒント1回以内で10回正解する」みたいなのを追加したくなったときのためにcounterにしておいたほうが良いかなと思いました

2021-11-16 03:00 UTC, hideo54 commented on bungo-quiz/index.ts
> +  const { data } = await axios.get<string>(
よく見たら shift-jis の decoder 噛ませてたわ。ずび…

2021-11-16 05:00 UTC, hideo54 approved these changes
よさそー

2021-11-16 05:00 UTC, hideo54 commented on bungo-quiz/index.ts
> +                if (index < arr.length - 1)
ここ、if 文の中身が同じで if の意味がなくなってますが、意図的なものですか?

2021-11-16 11:18 UTC, Yosshi999 commented on achievements/achievements.ts
> +	},
counterにすると1回だけでなく複数回の実績も入れないとテストが落ちるんですが、実績名が思いつかなかったので1回のみにしています

2021-11-16 11:22 UTC, Yosshi999 commented on bungo-quiz/index.ts
> +                if (index < arr.length - 1)
あーほんとだ
文豪クイズの方をコピペしたときの跡ですね　消しておきます

2021-11-16 11:22 UTC, Yosshi999 commented on bungo-quiz/index.ts
> +                  return { channel, text: `次のヒントです！\n> ${text}` }
```suggestion
                return { channel, text: `次のヒントです！\n> ${text}` }
```

2021-11-16 11:32 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/147086)

2021-11-16 11:33 UTC, Yosshi999 commented on bungo-quiz/index.ts
> +              ...hints.slice(1, -1).map((text, index, arr) => {
えーい知ったことか

2021-11-16 11:33 UTC, merged