add kirarafantasia ate quiz achievements
tsg-ut/slackbot pull request #548
Opened 2021-11-14 19:46 UTC by naan4UGen

きららファンタジア当てクイズの実績を生やしました

2021-11-15 04:35 UTC, settyan117 requested changes

2021-11-15 04:35 UTC, settyan117 commented on kirafan/quiz.ts
> +        if (result.hintIndex === 1) {
hintIndexはhintMessage(not problem)が投稿されるたびに+1されるので、first-hintのときは0です
```suggestion
        if (result.hintIndex === 0) {
```

2021-11-15 04:35 UTC, settyan117 commented on kirafan/quiz.ts
> +        }
first-hintと同様です
```suggestion
        if (result.hintIndex <= 1) {
          await increment(result.correctAnswerer, 'kirafan-answer-second-hint');
        }
        if (result.hintIndex <= 2) {
          await increment(result.correctAnswerer, 'kirafan-answer-third-hint');
        }
```

2021-11-15 04:35 UTC, settyan117 commented on achievements/achievements.ts
> +	},
category分けてもええんちゃう？とは思います

2021-11-15 10:45 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/146953)

2021-11-15 10:45 UTC, hakatashi commented on achievements/achievements.ts
> +	},
ディレクトリ違うし分けて良さそう `kirafan` か `ate-quiz`

2021-11-15 18:06 UTC, settyan117 requested changes

2021-11-15 18:06 UTC, settyan117 commented on achievements/achievements.ts
> +
category, なおってなさそう

2021-11-15 22:17 UTC, naan4UGen commented on achievements/achievements.ts
> +
なおって へんやん

2021-11-16 07:45 UTC, settyan117 approved these changes
:yosasou:
ただしクイズ本体が安定するまでマージは待ってほしいです

2022-04-21 06:20 UTC, naan4UGen commented
:eyes:

2022-04-21 06:59 UTC, naan4UGen commented
マージしても、ええか

2022-04-21 07:07 UTC, settyan117 commented
eeyo

2022-04-21 07:07 UTC, naan4UGen commented
ありがとう…

2022-04-21 07:07 UTC, merged