implement wadokaichin
tsg-ut/slackbot pull request #708
Opened 2022-08-09 15:52 UTC by satos---jp

和同開珎ゲームを実装しました。
実装する際にslackMockとatequizに手を加えたので特にそのあたりののレビューお願いします。

HARDモード / 実績 についてはのちのち実装してまた別のPRを作ろうと思っています。

2022-08-10 15:00 UTC, hakatashi requested changes

2022-08-10 15:12 UTC, settyan117 requested changes

2022-08-10 15:12 UTC, settyan117 commented on atequiz/index.ts
> -    this.problem = JSON.parse(JSON.stringify(problem));
できれば問題はコピーしたかった気持ちもありますが、まあ今のところは多分問題ないのでええか！ｗ

2022-08-10 15:12 UTC, settyan117 commented on atequiz/index.ts
> +    // Listeners should be added before postMessage is called.
:kashikoi:

2022-08-10 15:15 UTC, settyan117 commented on atequiz/index.ts
> +    this.problem = problem;
オブジェクトの要素に関数の存在を想定すると、もとのままだとこわれそう

2022-08-11 08:59 UTC, settyan117 approved these changes
atequiz部分は
![LGTM](https://image.lgtmoon.dev/177148)
**取り消します**（ずび）

2022-08-11 08:59 UTC, settyan117 commented on atequiz/index.ts
> +  solvedMessageGen(answer: string): ChatPostMessageArguments {
GenはQuizの方に入れたんですね～ 良いと思います
（基本的に問題依存ではなくてクイズbot依存になりそうですしね）

2022-08-11 09:08 UTC, settyan117 requested changes

2022-08-11 09:08 UTC, settyan117 commented on atequiz/index.ts
> +  solvedMessageGen(answer: string): ChatPostMessageArguments {
とおもったけど、Genを上書きするときは[[!user]]とかの置換はいらないと思うので、デフォルトのsolvedMessageGenの中身を「solvedMessageをreplaceKeysに従って置き換える」にして、postMessage関数内でのreplace処理をやめると偉いような気もします

2022-08-11 17:25 UTC, satos---jp commented on atequiz/index.ts
> +  solvedMessage: ChatPostMessageArguments | ((answer:string) => ChatPostMessageArguments);
solvedMessageGenを作りました。

2022-08-11 17:25 UTC, satos---jp commented on atequiz/index.ts
> +    this.problem = problem;
関数が要素に必要なくなったので元のほうに戻しました。

2022-08-11 17:27 UTC, satos---jp commented on wadokaichin/index.test.ts
> +]).flat();
なるほど。そっちにしてみました。

2022-08-11 17:27 UTC, satos---jp commented on wadokaichin/index.test.ts
> +    await (new Promise((res) => res(0)));
これ`await new Promise(process.nextTick);`だとdeadlockするっぽいです...(とりあえずdeadlockする旨を付け加えたコメントを残しました)

2022-08-11 17:27 UTC, satos---jp commented on wadokaichin/index.ts
> +:_::_: ${problem[0][0]}
使ってみました。

2022-08-11 17:28 UTC, satos---jp commented on wadokaichin/index.ts
> +  }));
promises使ってみました。(加えて、`__mock__/fs.js`に`promises.writeFile`を追加しました。)

2022-08-11 17:32 UTC, satos---jp commented on wadokaichin/index.ts
> +const kanjisPromise : Promise<string[]> = new Promise((resolve) => {
これなんですけど、Promiseで包んでる時点で最初の1回だけLoadされる(それとも僕のPromiseの理解が間違っている...?)ので、わざわざLoaderで包まなくとも所望の挙動を実現できる(むしろLoaderを使うといちいちloadを呼ばなきゃいけなくなる)気がするのですが、どうでしょうか。

2022-08-11 17:32 UTC, satos---jp commented on wadokaichin/index.ts
> +    return await getDictionary();
消しました。(要らんですねこれ)

2022-08-11 17:32 UTC, satos---jp commented on wadokaichin/data/gen_joyo.py
> +import regex
移動しました。

2022-08-11 17:33 UTC, satos---jp commented on wadokaichin/index.ts
> +            for(;;){
`parser.on('data')`に書き換えました。

2022-08-11 17:33 UTC, satos---jp commented on wadokaichin/index.ts
> +    await new Promise((resolve,error) => {
直しました。

2022-08-11 17:34 UTC, satos---jp commented on wadokaichin/index.ts
> +    if(cs.some((c) => !kanjis.includes(c))){
kanjisに対してhasを使うところでは前計算したkanjisSetを使うようにしました。(他のところではkanjisはarrayのままでよさそうです。)

2022-08-11 17:34 UTC, satos---jp commented on wadokaichin/index.ts
> +  });
直しました。

2022-08-11 17:35 UTC, satos---jp commented on wadokaichin/index.ts
> +  for(;;){
直しました。

2022-08-11 17:35 UTC, satos---jp commented on wadokaichin/index.ts
> +//   const repr = `
消しました。

2022-08-11 17:36 UTC, satos---jp commented on wadokaichin/index.ts
> +    mutex.runExclusive(async () => {
あんまり想定していない気がしてきたので、既起動時には起動するかわりに:running:リアクションを付けるようにしました。

2022-08-11 17:36 UTC, satos---jp commented on atequiz/index.ts
> +  solvedMessage: ChatPostMessageArguments | ((answer:string) => ChatPostMessageArguments);
分けました。

2022-08-11 17:38 UTC, satos---jp commented on atequiz/index.ts
> +  solvedMessageGen(answer: string): ChatPostMessageArguments {
replace処理をsolvedMassageGen内で行うようにしました。同時に、postMessageから不要になったreplaces引数を消しました。

2022-08-11 17:38 UTC, settyan117 commented on wadokaichin/index.ts
> +    mutex.runExclusive(async () => {
遡って探すの大変な場合があるので、起動中のゲームのpostのリンクをリプするとか、ゲーム内のスレッドでbroadcastするとかしてくれるとうれしいきもします

2022-08-11 17:42 UTC, satos---jp commented on wadokaichin/index.ts
> +    mutex.runExclusive(async () => {
クイズの制限時間が3分なので探すの大変にはならんやろと高をくくっていますがどうでしょう(想定したシチュエーションは、一回和同開珎が終わったので複数人が同時にまた和同開珎と叫ぶシチュエーションです)

2022-08-11 17:43 UTC, satos---jp commented on wadokaichin/index.ts
> +    mutex.runExclusive(async () => {
(あと現在のatequizの仕組みでリプ/broadcastさせるの面倒な気がします...)

2022-08-11 18:01 UTC, settyan117 commented on wadokaichin/index.ts
> +    mutex.runExclusive(async () => {
リプというのは、起動しようとしたpost(「和同開珎」)自体にくっつけるリプのつもりでした(これはAteQuizの管轄外なのであまり関係なさそう まあたしかにいらないかも)
ゲームスレッドにリプを入れるのがめんどいのは、たしかに (何らかの方法でtsだけ通知できるようにできるといいかもやけど、めんどそうやな)

2022-08-12 16:10 UTC, hakatashi commented on wadokaichin/index.ts
> +const kanjisPromise : Promise<string[]> = new Promise((resolve) => {
slackbot起動時にすべてのBOTの初期化を行うと重たい (&メモリ使用量が多くなる) ので最初に使用するときに初期化したいという気持ちがあります。が、まあどうしても最初に読み込みたいならそのままでもよいです

2022-08-12 16:14 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/177114)

多少コメントが残ってるけど、よさそう

2022-08-12 18:31 UTC, satos---jp commented on wadokaichin/index.ts
> +const kanjisPromise : Promise<string[]> = new Promise((resolve) => {
なるほど。最初が重くなるの確かによくなさそうなのでLoaderを使うようにしました。

2022-08-12 18:49 UTC, satos---jp commented on atequiz/index.ts
> +
> もとの postMessage と同じように [置換前, 置換後] の配列 replaces を引数にとるかたちの実装

これに関してなのですが、どういう実装への修正を想定していますか？(例えば、僕はreplaceKeys処理をpostMessageから消してしまったのですが、それを残しておく感じですか？)

それともsolvedMessageGenが引数として置換配列を受け取る感じになりますか？(置換配列を受け取る実装の場合は、solvedMessageGenを上書きしたい人(例えば今回の僕)がいた場合、外から「置換配列の中でthis.replaceKeys.correctAnswererに紐づいている値をuserとして取り出す」みたいなコードを書く必要があって、あんまり筋としてよろしくない気がします)

2022-08-13 04:57 UTC, settyan117 commented on atequiz/index.ts
> +
たしかに置換配列を渡す実装だと結局start()をいじらないといけなくてつらそうなんですよね
（）内に書いた「postをまるまる渡しちゃう」みたいな実装がえらい気がしています

2022-08-13 06:57 UTC, satos---jp commented on atequiz/index.ts
> +
solvedMessageGenがpostを受け取るようにしました(型はanyですが...)

2022-08-13 06:58 UTC, settyan117 approved these changes
:bow:

2022-08-13 07:16 UTC, merged