キャラ当てクイズをanimeから分離，なもり当てクイズとIxy当てクイズを追加
tsg-ut/slackbot pull request #769
Opened 2022-11-12 19:19 UTC by settyan117

「なもり当てクイズ」でキャラ当てクイズが起動していたので，ちゃんとなもりさんのみのクイズが出るようにしました．ついでにIxy当てクイズも実装しました．

これにともなって，キャラ当てクイズを anime フォルダから分離して，AteQuizを利用する実装に変更しました．

2022-11-14 00:36 UTC, settyan117 commented on character-quiz/index.ts
> +import { ChatPostMessageArguments } from '@slack/web-api';
これ1行目にまとめるべきですね

2022-11-24 00:26 UTC, hakatashi requested changes

2022-11-24 00:26 UTC, hakatashi commented on character-quiz/index.ts
> +        message.text.match(/^(キャラ|なもり|Ixy)当てクイズs$/)
[MUST] このs何

2022-11-24 00:26 UTC, hakatashi commented on character-quiz/index.ts
> +
[MUST] コメントアウトは消してください

2022-11-24 00:26 UTC, hakatashi commented on character-quiz/index.ts
> +    // note: Originally, typicalAteQuizHintTexts is from anime/namori.ts
[QUESTION] このコメントはどういう意味ですか?

2022-11-24 00:26 UTC, hakatashi commented on character-quiz/.eslintrc.json
> +{
[SHOULD] eslintrcも前のanimeディレクトリのやつと同じであると嬉しいですね

2022-11-24 00:26 UTC, hakatashi commented on character-quiz/index.ts
> +]);
[MAY]

```suggestion
const loaderNamori = new Loader<CharacterData[]>(() => loadCharacters('namori'));
```

2022-11-24 00:26 UTC, hakatashi commented on character-quiz/index.ts
> +const loaderIxy = new Loader<CharacterData[]>(async () => [
[MAY] ditto

2022-11-24 02:23 UTC, settyan117 commented on character-quiz/index.ts
> +        message.text.match(/^(キャラ|なもり|Ixy)当てクイズs$/)
アッ (テスト用に変えていたのを忘れてました...)

2022-11-24 02:25 UTC, settyan117 commented on character-quiz/index.ts
> +    // note: Originally, typicalAteQuizHintTexts is from anime/namori.ts
このプルリクでtypicalAteQuizHintTextsの出自が消えてしまうので、敬意を表しています(？)

2022-11-24 06:55 UTC, settyan117 commented
なおしました

2022-11-27 00:33 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/188700)

2022-11-27 00:36 UTC, settyan117 commented
やったー

2022-11-27 00:36 UTC, merged