add hangman-de-hangman achievement
tsg-ut/slackbot pull request #779
Opened 2022-12-18 09:46 UTC by Szkieletor37

#473 を実装

2022-12-18 09:53 UTC, hakatashi requested changes

2022-12-18 09:53 UTC, hakatashi commented on achievements/achievements.ts
> +
[SHOULD] 関係ない変更

2022-12-18 09:53 UTC, hakatashi commented on achievements/achievements.ts
> +		id: 'hangman-de-hangman',
[MUST] 他の実績idに合わせて可能な限り英語を使用するようにしてください

2022-12-21 03:31 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/188700)

2022-12-21 04:03 UTC, merged

2023-01-01 04:13 UTC, hideo54 commented
これ天才すぎてビビりました