Mahjong command implement
tsg-ut/slackbot pull request #783
Opened 2022-12-25 12:33 UTC by Szkieletor37

#553  で要望されていたコマンドを、ドラ表示の方だけ「ドラ牌」として先に実装しました。

2022-12-25 14:12 UTC, hakatashi requested changes

2022-12-25 14:12 UTC, hakatashi commented on mahjong/index.js
> +			if(text === 'ドラ牌') {
[SHOULD] プルリク提出前にはlintを実行してください

2022-12-25 14:12 UTC, hakatashi commented on mahjong/index.js
> +				postMessage(source`
[SHOULD] 埋め込む変数が一つの場合はテンプレートリテラルを使用する必要はありません

2022-12-25 14:12 UTC, hakatashi commented on mahjong/index.js
> +					${state.ドラ表示牌s.map((牌) => 牌ToName(牌)).join(' ')}
[SHOULD] 「ドラ牌」と打ち込んだらドラ表示牌じゃなくてドラが表示されるほうが直感的に感じる。隣の牌を出してあげる実装の方がいいと思います

2022-12-27 12:46 UTC, Szkieletor37 commented
ドラ牌を示す実装が面倒になりそうだったのでドラ表示牌をそのまま変更する形に逃げてしまった

2023-01-01 06:26 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/192815)

2023-01-01 10:09 UTC, merged