Mahjong 手牌表示 implement
tsg-ut/slackbot pull request #787
Opened 2023-01-04 02:23 UTC by Szkieletor37

#553 

画像が何らかの原因で取ってこられなかったときのために、手牌表示コマンドを実装した。
採譜表示で12r588m239p467s東白白のように表記。
ドラ表示牌コマンドと統合した。

2023-01-04 02:26 UTC, Szkieletor37 commented
表示例→https://tsg-ut.slack.com/archives/C7AAX50QY/p1672799176007259

2023-01-04 03:27 UTC, hakatashi requested changes

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +	const 採譜表示 = 採譜表示s[normalized牌.codePointAt(0) - 0x1F000];
[SHOULD] 「採譜」「表示」は日本語固有の用語ではないので英語で表記してください

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +	...(漢数字s.map((漢数字) => `${漢数字s.indexOf(漢数字) + 1}m`)),
[MAY] 「漢数字s」変数を使用する必要はなさそう?

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +				${採譜表示ed手牌.slice(0, 採譜表示ed手牌.lastIndexOf('m') + 1).replace(/m/g, '')}m${採譜表示ed手牌.slice(採譜表示ed手牌.lastIndexOf('m') + 1, 採譜表示ed手牌.lastIndexOf('p') + 1).replace(/p/g, '')}p${採譜表示ed手牌.slice(採譜表示ed手牌.l
[SHOULD] 1行が長すぎます。変数を切り出すか処理を単純化して100文字前後に収まるようにしてください。

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +				${採譜表示ed手牌.slice(0, 採譜表示ed手牌.lastIndexOf('m') + 1).replace(/m/g, '')}m${採譜表示ed手牌.slice(採譜表示ed手牌.lastIndexOf('m') + 1, 採譜表示ed手牌.lastIndexOf('p') + 1).replace(/p/g, '')}p${採譜表示ed手牌.slice(採譜表示ed手牌.l
[SHOULD] 手牌がマンピンソー字牌の準に理牌されていることを前提とした実装ですが、この順番はすでに「牌Orders」という変数で定義されています。片方を修正したときに挙動がバグらないようにこの変数を参照した処理に置き換えてください。

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +				${採譜表示ed手牌.slice(0, 採譜表示ed手牌.lastIndexOf('m') + 1).replace(/m/g, '')}m${採譜表示ed手牌.slice(採譜表示ed手牌.lastIndexOf('m') + 1, 採譜表示ed手牌.lastIndexOf('p') + 1).replace(/p/g, '')}p${採譜表示ed手牌.slice(採譜表示ed手牌.l
[MAY] 複数行にまたがるテンプレート記法を用いる際はインデントを一つ下げてください

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +				ドラ表示牌:${state.ドラ表示牌s.map((牌) => 牌ToName(牌)).join(' ')}
```suggestion
				ドラ表示牌: ${state.ドラ表示牌s.map((牌) => 牌ToName(牌)).join(' ')}
```

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +			if (text === '手牌表示') {
[MAY] 「残り牌」コマンドと統一するためにコマンド名は「手牌」にするのがよいと思います

2023-01-04 03:27 UTC, hakatashi commented on mahjong/index.js
> +	'r5m', 'r5s', 'r5p',
[QUESTION] この赤ドラの3つは使われていますか?

2023-01-04 03:32 UTC, Szkieletor37 commented on mahjong/index.js
> +	'r5m', 'r5s', 'r5p',
使っていないので、消した方がよいでしょうか。

2023-01-04 06:35 UTC, hakatashi commented on mahjong/index.js
> +	'r5m', 'r5s', 'r5p',
デッドコードなら、消したほうがよさそう

2023-01-12 12:39 UTC, Szkieletor37 commented on mahjong/index.js
> +				${採譜表示ed手牌.slice(0, 採譜表示ed手牌.lastIndexOf('m') + 1).replace(/m/g, '')}m${採譜表示ed手牌.slice(採譜表示ed手牌.lastIndexOf('m') + 1, 採譜表示ed手牌.lastIndexOf('p') + 1).replace(/p/g, '')}p${採譜表示ed手牌.slice(採譜表示ed手牌.l
表示形式上「萬子ならm, 筒子ならs, 索子ならsを付け加える」という処理をする必要があったため、romaji牌Ordersという変数を作りました。

2023-01-12 12:54 UTC, hakatashi requested changes

2023-01-12 12:54 UTC, hakatashi commented on mahjong/index.js
> +					${convertedIntoNumerals手牌Array.join('').replace(/,/g, '')}
[SHOULD] convertedIntoNumerals手牌Arrayは二次元配列なので、join関数の実行時にArrayからStringへのimplicitな変換が行われています。ArrayからStringへのimplicitな変換は利用しないでください (つまり、join関数はStringの配列にのみ適用してください)。

2023-01-12 12:54 UTC, hakatashi commented on mahjong/index.js
> +				convertedIntoNumerals手牌Array.forEach((牌Array, index) => 牌Array.push(Romaji牌Orders[index]));
[SHOULD] forEachは使用しないでください (for-ofを代わりに使用してください)

2023-01-12 12:54 UTC, hakatashi commented on mahjong/index.js
> +				const categorized手牌Array = Array.from(牌Orders, (_, index) => sort(state.手牌).filter((牌) => get牌Type(牌) === 牌Orders[index]));
[MAY] 処理の内容が分かりづらいので、[lodash.groupBy](https://lodash.com/docs/#groupBy)などのユーティリティ関数を使用することなどを検討してください。

[MAY] sortが配列の要素数だけ実行されています。そこまで重い処理ではないですが、1度で済む処理は1回しか行わないことが理想的です。

[INFO] ちなみに、上を修正するならこう書く必要はないですが、

```suggestion
				const categorized手牌Array = 牌Orders.map((牌Type) => sort(state.手牌).filter((牌) => get牌Type(牌) === 牌Type));
```

と簡潔に書くことができると思います。

2023-01-12 12:54 UTC, hakatashi commented on mahjong/index.js
> +	...[...Array(9)].map((_, i) => `${i + 1}`),
[MAY] [lodash.range](https://lodash.com/docs/#range)を使うとよいです

2023-01-12 12:54 UTC, hakatashi commented on mahjong/index.js
> +const romaji牌Orders = ['m', 'p', 's', ''];
[nit] 本当に必要なのは牌種の漢字表記とローマ字表記の対応表だと思うので、

```js
new Map([
  ['萬子', 'm'],
  ...
])
```

のような形で定義されていることが理想的だと思います (余裕がなければ直さなくても良いです)

2023-01-23 03:40 UTC, Szkieletor37 commented on mahjong/index.js
> +				const categorized手牌Array = Array.from(牌Orders, (_, index) => sort(state.手牌).filter((牌) => get牌Type(牌) === 牌Orders[index]));
lodash.groupBy の返り値が連想配列になってしまうこともあり、hakatashiが提示してくれた修正にしました。

2023-01-23 03:40 UTC, Szkieletor37 commented on mahjong/index.js
> +const romaji牌Orders = ['m', 'p', 's', ''];
余裕がないので、直しませんでした。

2023-01-23 04:23 UTC, hakatashi requested changes

2023-01-23 04:23 UTC, hakatashi commented on mahjong/index.js
> +				);
[nit] reduceは難しいので使用を避けられる場合は避けると吉です。

今回の場合↓のようにlodash.zipを使用して書くと簡潔に書けると思います。

```suggestion
				const convertedIntoNumerals手牌 =
					zip(convertedIntoNumerals手牌Array, romaji牌Orders)
						.map((牌String, romaji牌Type) => 牌String + romaji牌Type)
						.join('');
```

2023-01-23 04:23 UTC, hakatashi commented on mahjong/index.js
> +				// 12r588m239p467s東白白 のように表記
[MUST] このコードは、萬子が1枚もない場合など特定の牌種が欠けている場合に正常に動作しますか?

動かしてないけど、一索・二索・東が手牌のときに `mp12s東` みたいになる気がする

2023-01-23 04:23 UTC, hakatashi commented on mahjong/index.js
> +	...range(1,10),
[SHOULD] Lintされてなさそう

2023-01-23 05:18 UTC, Szkieletor37 commented on mahjong/index.js
> +				// 12r588m239p467s東白白 のように表記
reduce を lodash.zip に置き換える過程で、特定の牌種が1枚もない場合は `romaji牌Type` を追加しないようにしました。

2023-01-23 05:27 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/194702)

2023-01-23 05:27 UTC, hakatashi commented on mahjong/index.js
> +							return 牌String;
[INFO] 直すほどではないけど、早期リターンを行う場合は例外処理を先に書くと読みやすいです。

2023-01-23 05:27 UTC, hakatashi commented on mahjong/index.js
> +				state.手牌 = sort(state.手牌)
[MAY] 手牌表示でstateが書き換わる可能性があるの、よくなさそう ローカル変数にしたほうが安全だと思います

2023-01-23 05:43 UTC, merged