achievements: すでに解除者のいるprofessional実績に上位実績を追加
tsg-ut/slackbot pull request #807
Opened 2023-02-19 12:14 UTC by hakatashi

2023-02-19 12:38 UTC, settyan117 commented
こいつら専用の上位 difficulty 追加してもよさそう？

2023-02-19 12:41 UTC, hakatashi commented
フムー よさそう

legendとかかな

2023-02-19 12:44 UTC, settyan117 commented
![image](https://user-images.githubusercontent.com/7821320/219948742-2993fc9e-fe3c-4035-aad1-f287b78a07e0.png)

2023-02-19 12:46 UTC, naan4UGen requested changes

2023-02-19 12:46 UTC, naan4UGen commented on achievements/achievements.ts
> +	},
```suggestion
	{
		id: 'kirafan-answer-first-hint-100',
		difficulty: 'professional',
		title: 'きららさんといっしょ',
		condition: 'きらファン当てクイズでヒント1回以内で100回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer-first-hint',
		value: 100,
	},
	{
		id: 'kirafan-answer-first-hint-1000',
		difficulty: 'professional',
		title: '新たなる聖典の紡ぎ手',
		condition: 'きらファン当てクイズでヒント1回以内で1000回正解する',
		category: 'kirafan',
		counter: 'kirafan-answer-first-hint',
		value: 1000,
	},
```
きらファン当てクイズヒント1回の実績はきららファンタジアオリジナルキャラクターであるところのランプさんを題材にしているので、実績名はこちらのほうが嬉しい

2023-02-19 12:46 UTC, naan4UGen commented on achievements/achievements.ts
> +		title: '七賢者',
```suggestion
		title: 'スクライブギルド長',
```
きらファン当てクイズeasyのヒント1回はきららファンタジアオリジナルキャラクターであるところのメディアさんを題材にしているので、実績名はこちらのほうが嬉しい

2023-02-19 12:47 UTC, naan4UGen approved these changes

2023-02-19 12:49 UTC, naan4UGen commented
![image](https://user-images.githubusercontent.com/47272321/219949010-baab43a7-9e0e-430e-9686-ea3927d2cde3.png)

2023-02-21 18:47 UTC, hakatashi commented
ウムー 新難易度の追加はちょっと考えることが多いのでとりあえず後回しにして、マージを優先します

2023-02-22 00:18 UTC, settyan117 commented
今回の追加実績を一覧にして、Issue立ててもらえるとうれしいです(あとで確認しやすいため)

2023-02-22 00:23 UTC, settyan117 approved these changes
![LGTM](https://image.lgtmoon.dev/198423)

2023-02-22 06:24 UTC, merged