オリジナルのキャラクターに対応
tsg-ut/slackbot pull request #849
Opened 2023-08-22 11:26 UTC by settyan117

名前が空のキャラクターを弾くようにした

2023-08-22 16:09 UTC, hakatashi requested changes

2023-08-22 16:09 UTC, hakatashi commented on character-quiz/index.ts
> +			const characterRubys = characterRuby.split(/[、&]/).filter((name) => name !== '');
```suggestion
			const characterNames = characterName.split(/[、&]/).filter((name) => name !== '');
			const characterRubys = characterRuby.split(/[、&]/).filter((name) => name !== '');
			
			if (characterNames.length === 0 || characterRubys.length === 0) {
				return null;
			}
```

にして、filterでnullを弾くようにしたい (型は type guard でなんとか)

2023-08-23 09:53 UTC, settyan117 commented on character-quiz/index.ts
> +			const characterRubys = characterRuby.split(/[、&]/).filter((name) => name !== '');
オリキャラもキャラクターではあるので、一旦は CharacterData にしてしまってあとから弾きたくない？

2024-04-25 04:10 UTC, hakatashi approved these changes

2024-04-25 04:15 UTC, merged