90日間投稿のないチャンネルをアーカイブするBOTを作成
tsg-ut/slackbot pull request #879
Opened 2024-03-17 16:18 UTC by hakatashi

![image](https://github.com/tsg-ut/slackbot/assets/3126484/9e42e696-aa03-4c56-b142-1bb9f582ee01)

![image](https://github.com/tsg-ut/slackbot/assets/3126484/698ebb44-0412-488e-8f8c-da126bfbf929)

2024-04-28 14:20 UTC, JP3BGY requested changes
ハードコードされていた部分について一応コメント

2024-04-28 14:20 UTC, JP3BGY commented on auto-archiver/index.test.ts
> +			'<!channel> このチャンネルには90日以上BOT以外のメッセージが投稿されていません。',
`90` → `${ARCHIVE_LIMIT_DAYS}`

2024-04-28 14:20 UTC, JP3BGY commented on auto-archiver/index.test.ts
> +			'<!channel> このチャンネルには90日以上BOT以外のメッセージが投稿されていません。',
`90` → `${ARCHIVE_LIMIT_DAYS}`

2024-04-28 14:20 UTC, JP3BGY commented on auto-archiver/index.test.ts
> +			expire: FAKE_NOW.getTime() + 30 * 24 * 60 * 60 * 1000,
`30` → `ARCHIVE_SNOOZE_DAYS`
or
`30 * ... * 1000` → `ARCHIVE_SNOOZE_DURATION`

2024-04-28 14:20 UTC, JP3BGY commented on auto-archiver/index.ts
> +	* 「使用しない」を押す、もしくは24時間以内に応答がない場合、チャンネルはアーカイブされます。
`24` → `${ARCHIVE_WAIT_HOURS}`

2024-04-28 14:20 UTC, JP3BGY commented on auto-archiver/index.ts
> +					text: '24時間以内に応答がなかったため、チャンネルをアーカイブしました。',
`24` → `${ARCHIVE_WAIT_HOURS}`

2024-04-28 18:14 UTC, hideo54 approved these changes
ﾖｯｻｿｿ

2024-04-30 15:11 UTC, iwashiira commented
動かしてみたい👀

2024-04-30 15:13 UTC, iwashiira approved these changes
見ました

2024-05-03 17:48 UTC, JP3BGY requested changes
metaチャンネル参照

2024-05-03 17:48 UTC, JP3BGY commented on auto-archiver/index.ts
> +const ARCHIVE_SNOOZE_DAYS = 30;
`30` → `90`

2024-05-10 15:26 UTC, hakatashi commented on auto-archiver/index.test.ts
> +			'<!channel> このチャンネルには90日以上BOT以外のメッセージが投稿されていません。',
Discussed offline.

これはユニットテストでテストしたい内容なので定数化しないでおきます。

2024-05-10 15:26 UTC, hakatashi commented on auto-archiver/index.test.ts
> +			'<!channel> このチャンネルには90日以上BOT以外のメッセージが投稿されていません。',
Discussed offline.

これはユニットテストでテストしたい内容なので定数化しないでおきます。

2024-05-10 15:26 UTC, hakatashi commented on auto-archiver/index.test.ts
> +			'<!channel> このチャンネルには90日以上BOT以外のメッセージが投稿されていません。',
Discussed offline.

これはユニットテストでテストしたい内容なので定数化しないでおきます。

2024-05-10 15:26 UTC, hakatashi commented on auto-archiver/index.test.ts
> +	it('should not remind to archive if message is posted within 90 days', async () => {
Discussed offline.

これはユニットテストでテストしたい内容なので定数化しないでおきます。

2024-05-10 15:33 UTC, JP3BGY approved these changes
LGTM

2024-05-10 15:41 UTC, merged