"X" 発言に Twitter スタンプを送る
tsg-ut/slackbot pull request #897
Opened 2024-05-21 07:15 UTC by Sqrt10-31622776

"Twitter" を含むメッセージに対して "X" スタンプが来るのに対抗して，"X"（単語中のものは含まない）を含むメッセージに対して "Twitter" スタンプを送るようにしました
初めて TSG の slackbot をいじるので粗祖をしていたらごめんなさい
デバッグとかしていませんが多分動くと信じてます

2024-05-21 07:50 UTC, settyan117 commented
http-local-fwd をリポジトリ内に clone したことで submodule 扱いになってしまっていそう

2024-05-21 10:46 UTC, Sqrt10-31622776 commented
消してみました，これで行けますか

2024-05-21 11:37 UTC, hakatashi requested changes
[MAY] 動作確認はしましたか? 可能な限りされていることが望ましいです。動作確認をした場合はスクリーンショットをプルリクの最初のメッセージに貼り付けてください。

[MAY] sushi-botにはユニットテストがあるので、可能な限り変更に対応するテストケースが追加されていることが望ましいです。

2024-05-21 11:37 UTC, hakatashi commented on sushi-bot/index.ts
> +        {
[SHOULD] インデントがスペースになっています。周りに合わせてください

2024-09-15 16:25 UTC, Sqrt10-31622776 commented on sushi-bot/index.ts
> +        {
動作確認をしました．
ユニットテストを追加しました．

2025-04-02 09:46 UTC, hakatashi commented
#924 にて解決済み

2025-04-02 09:46 UTC, closed without merging